project:
  type: website

website:
  title: "A Random Walk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:tutorials
      - sidebar:slides
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/jfking50
  sidebar:
    - id: tutorials
      title: "Tutorials"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - href: tutorial/slr.qmd
          text: Simple Linear Regression
        - href: tutorial/lm_assumptions.qmd
          text: Linear Model Assumptions
        - href: tutorial/mlr.qmd
          text: Multiple Linear Regression
        - href: tutorial/model_selection.qmd
          text: Model Selection
        - href: tutorial/transform.qmd
          text: Variable Transformation
        - href: tutorial/logistic.qmd
          text: Logistic Regression
        - href: tutorial/advanced.qmd
          text: Advanced Designs
        - href: tutorial/np_anova.qmd
          text: Nonparametric ANOVA
        - href: tutorial/gam.qmd
          text: Generalized Additive Models
        - href: tutorial/svm.qmd
          text: Support Vector Machines
        - href: tutorial/random_forest.qmd
          text: Random Forests
        - href: tutorial/nn_regression.qmd
          text: Neural Network Regression
    - id: slides
      title: "Presentations"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - href: presentations/doe.qmd
          text: Design of Experiments
  page-footer:
    background: light
    left: "Copyright 2022, John King"
  page-navigation: true

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css

editor: visual

execute:
  freeze: auto