{
  "hash": "825b7f40ac0c6fc56f45f3a082df9969",
  "result": {
    "markdown": "---\ntitle: \"Multiple Linear Regression\"\nauthor: \"John King\"\ndate: \"5/23/2020\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    df-print: paged\nexecute: \n  warning: false\n  echo: true\n---\n\n\nIn the previous section we considered just one predictor and one response. The linear model can be expanded to include multiple predictors by simply adding terms to the equation:\n\n$$y = \\beta_{0} + \\beta_{1}x_{1}+ \\beta_{2}x_{2} + ... + \\beta_{(p-1)}x_{(p-1)} + \\varepsilon$$\n\nWith one predictor, least squares regression produces a regression line. With two predictors, we get a regression plane (shown below), and so on up to a $(p-1)$ dimensional hyperplane.\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-2a8e9539872343d5916c\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-2a8e9539872343d5916c\">{\"x\":{\"visdat\":{\"2ba04752713\":[\"function () \",\"plotlyVisDat\"],\"2ba032f721a3\":[\"function () \",\"data\"],\"2ba061989d6\":[\"function () \",\"data\"]},\"cur_data\":\"2ba061989d6\",\"attrs\":{\"2ba032f721a3\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":7},\"showlegend\":false,\"inherit\":true},\"2ba061989d6\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"mesh3d\",\"facecolor\":[\"blue\",\"blue\"],\"opacity\":0.75,\"showlegend\":false,\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Best Fit Plane\",\"showlegend\":false,\"scene\":{\"xaxis\":{\"range\":[0,10],\"title\":\"x1\"},\"yaxis\":{\"range\":[0,10],\"title\":\"x2\"},\"camera\":{\"eye\":{\"x\":0,\"y\":-2,\"z\":0.3}},\"zaxis\":{\"title\":\"y\"}},\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[9.14806043496355,9.37075413297862,2.86139534786344,8.30447626067325,6.41745518893003,5.19095949130133,7.36588314641267,1.3466659723781,6.56992290401831,7.05064784036949],\"y\":[4.5774177624844,7.19112251652405,9.34672247152776,2.55428824340925,4.62292822543532,9.40014522755519,9.78226428385824,1.17487361654639,4.74997081561014,5.60332746244967],\"z\":[5.99114356409588,7.11473922517624,3.22154518985722,4.26414945838675,4.41869783432461,5.3655056340129,4.57315445009747,1.46962155854145,2.1255277574059,5.95281211087115],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":7,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"showlegend\":false,\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"colorbar\":{\"title\":\"y<br />y\",\"ticklen\":2},\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":true,\"x\":[0,10,0,10],\"y\":[0,0,10,10],\"z\":[0.167243763471059,5.07605548829849,2.13181054993435,7.04062227476178],\"type\":\"mesh3d\",\"facecolor\":[\"blue\",\"blue\"],\"opacity\":0.75,\"showlegend\":false,\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n## Linear Algebra Solution\n\nWith two or more predictors, we can't solve for the linear model coefficients the same way we did for the one predictor case. Solving for the coefficients (the $\\beta$s) requires some linear algebra. Given a data set with $n$ observations and one predictor, the $y$ (response), $X$ (predictor), and $\\beta$ (coefficient) matrices are written as:\n\n$$y= \\begin{pmatrix} y_1 \\\\ \\vdots \\\\ y_n \\end{pmatrix} , X= \\begin{pmatrix} 1 & x_1 \\\\ \\vdots & \\vdots \\\\ 1 & x_n \\end{pmatrix}, \\beta= \\begin{pmatrix} \\beta_0 \\\\ \\beta_1 \\end{pmatrix}$$\n\nIncorporating the error term, we have:\n\n$$\\varepsilon= \\begin{pmatrix} \\varepsilon_1 \\\\ \\vdots \\\\ \\varepsilon_n \\end{pmatrix} = \\begin{pmatrix} y_1-\\beta_0-\\beta_1x_1 \\\\ \\vdots \\\\ y_n-\\beta_0-\\beta_1x_n \\end{pmatrix} = y-X\\beta$$\n\nOnce we solve for the coefficients, multiplying them by the predictors gives the estimated response, $\\hat{y}$.\n\n$$X\\beta \\equiv \\hat{y}$$\n\nWith multiple linear regression, we expand the $X$ and $\\beta$ matrices accordingly.\n\n$$y= \\begin{pmatrix} y_1 \\\\ \\vdots \\\\ y_n \\end{pmatrix} , X= \\begin{pmatrix} 1 & x_{11} & \\ldots & x_{1p-1} \\\\ \\vdots & \\vdots & \\ddots & \\vdots \\\\ 1 & x_{n1} & \\ldots & x_{np-1} \\end{pmatrix}, \\beta= \\begin{pmatrix} \\beta_0 \\\\ \\vdots \\\\ \\beta_{p-1} \\end{pmatrix}$$\n\nIncorporating error:\n\n$$\\varepsilon= \\begin{pmatrix} \\varepsilon_1 \\\\ \\vdots \\\\ \\varepsilon_n \\end{pmatrix} = \\begin{pmatrix} y_1-(\\beta_0-\\beta_1x_{11} + \\ldots + \\beta_{p-1}x_{1p-1}) \\\\ \\vdots \\\\ y_n-(\\beta_0-\\beta_1x_{n1} + \\ldots + \\beta_{p-1}x_{np-1}) \\end{pmatrix} = y-X\\beta$$\n\nHowever, notice that the final equation remains unchanged.\n\n$$X\\beta \\equiv \\hat{y}$$\n\nThe residual sum of squares (RSS) also remains unchanged, and so do the other equations that have RSS as a term, such as residual standard error and $R^2$. The following is an example of solving the system of equations for a case with two predictors and no error. Given $n=4$ observations, we have the following system of equations:\n\n$$x_0 = 10$$ $$x_0 + x_2 = 17$$ $$x_0 + x_1 = 15$$ $$x_0 + x_1 + x_2 = 22$$\n\nIn this example, we technically have all of the information we need to solve this system of equations without linear algebra, but we'll apply it anyway to demonstrate the method. Rewriting the above system of equations into matrix form gives:\n\n$$X= \\begin{pmatrix} 1 & 0 & 0 \\\\ 1 & 0 & 1 \\\\ 1 & 1 & 0 \\\\ 1 & 1 & 1 \\end{pmatrix}, y= \\begin{pmatrix} 10 \\\\ 17 \\\\ 15 \\\\ 22 \\end{pmatrix}$$\n\nOne way to solve for the $\\beta$ vector is to transpose the $X$ matrix and multiply it by the $X|y$ augmented matrix.\n\n$$X^TX|y = \\begin{pmatrix} 1&1&1&1 \\\\ 0&0&1&1 \\\\ 0&1&0&1 \\end{pmatrix} \\begin{pmatrix} 1&0&0&|&10 \\\\ 1&0&1&|&17 \\\\ 1&1&0&|&15 \\\\ 1&1&1&|&22 \\end{pmatrix} = \\begin{pmatrix} 4&2&2&|&64 \\\\ 2&2&1&|&37 \\\\ 2&1&2&|&39 \\end{pmatrix}$$\n\nUse Gaussian elimination to reduce the resulting matrix by first multiplying the top row by $-\\frac{1}{2}$ and adding those values to the second row.\n\n$$\\begin{pmatrix} 4&2&2&|&64 \\\\ 0&1&0&|&5 \\\\ 2&1&2&|&39 \\end{pmatrix}$$\n\nReduce further using the same process on the third row.\n\n$$\\begin{pmatrix} 4&2&2&|&64 \\\\ 0&1&0&|&5 \\\\ 0&0&1&|&7 \\end{pmatrix}$$\n\nWe find that\n\n$$\\beta_2 = 7$$ and\n\n$$\\beta_1 = 5$$\n\nand using back substitution we get\n\n$$4\\beta_0 + 2(5) + 2(7) = 64, \\enspace so \\enspace \\beta_0 = 10$$\n\nThe resulting equation:\n\n$$y=10+5x_1+7x_2$$\n\ndefines the best fit plane for this data, which is visualized below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-5bc403e1f7b162d7d6b0\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5bc403e1f7b162d7d6b0\">{\"x\":{\"visdat\":{\"2ba042444472\":[\"function () \",\"plotlyVisDat\"],\"2ba07e2a6219\":[\"function () \",\"data\"],\"2ba0567020fa\":[\"function () \",\"data\"]},\"cur_data\":\"2ba0567020fa\",\"attrs\":{\"2ba07e2a6219\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":7},\"showlegend\":false,\"inherit\":true},\"2ba0567020fa\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"mesh3d\",\"facecolor\":[\"blue\",\"blue\"],\"showlegend\":false,\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Best Fit Plane\",\"showlegend\":false,\"scene\":{\"camera\":{\"eye\":{\"x\":-1.5,\"y\":-1.5,\"z\":0.3}},\"xaxis\":{\"title\":\"x1\"},\"yaxis\":{\"title\":\"x2\"},\"zaxis\":{\"title\":\"y\"}},\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0,0,1,1],\"y\":[0,1,0,1],\"z\":[10,17,15,22],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":7,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"showlegend\":false,\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"colorbar\":{\"title\":\"y<br />y\",\"ticklen\":2},\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":true,\"x\":[0,0,1,1],\"y\":[0,1,0,1],\"z\":[10,17,15,22],\"type\":\"mesh3d\",\"facecolor\":[\"blue\",\"blue\"],\"showlegend\":false,\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nOf course, *R* has linear algebra functions, so we don't have to do all of that by hand. For example, we can solve for the $\\beta$ vector by multiplying both sides of the equation $X\\beta \\equiv \\hat{y}$ by $X^T$.\n\n$$X^TX\\beta = X^Ty$$\n\nSolving for $\\beta$, we get:\n\n$$\\beta=(X^TX)^{-1}X^Ty$$\n\nNow use `solve()` function to calculate the $\\beta$ vector (note that `solve()` inverts $X^TX$ automatically).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX = matrix(c(1,0,0,\n             1,0,1,\n             1,1,0,\n             1,1,1), byrow = TRUE, ncol=3)\n\ny = 10 + 5*X[, 2] + 7*X[, 3]\n\nsolve(t(X) %*% X) %*% (t(X) %*% y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1]\n[1,]   10\n[2,]    5\n[3,]    7\n```\n:::\n:::\n\n\nFitting a linear model in *R* using the `lm()` function produces coefficients identical to the above results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(y ~ X[, 2] + X[, 3]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      X[, 2]      X[, 3] \n         10           5           7 \n```\n:::\n:::\n\n\nTechnically, neither the `solve()` nor the `lm()` functions use Gaussian elimination when solving the system of equations. According to [this site](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-c/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem-routines.html), for overdetermined systems (where there are more equations than unknowns) like the example we're working with, they use QR factorization instead. The details of QR factorization are beyond the scope of this course, but are explained well on [these slides](http://www.seas.ucla.edu/~vandenbe/133A/lectures/ls.pdf) from a course at UCLA's School of Engineering and Applied Sciences. In essence, the $X$ matrix is decomposed into $Q$ and $R$ matrices that are substituted for $X$ in the equation.\n\n$$X^TX\\beta = X^Ty$$\n\n$$(QR)^T(QR)\\beta = (QR)^Ty$$\n\nSkipping a lot of math, we end up with:\n\n$$R\\beta=Q^Ty$$\n\nIn *R*, use `qr(X)` to decompose $X$, and then use `solve.qr()` to calculate the $\\beta$ vector.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQR = qr(X)\nsolve.qr(QR, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10  5  7\n```\n:::\n:::\n\n\nNow we'll make it a little more complicated by returning to the data set plotted at the beginning of this section. It consists of $n=10$ observations with random error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr # multiple linear regression data set\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"x1\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"x2\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"y\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"9.148060\",\"2\":\"4.577418\",\"3\":\"5.991144\"},{\"1\":\"9.370754\",\"2\":\"7.191123\",\"3\":\"7.114739\"},{\"1\":\"2.861395\",\"2\":\"9.346722\",\"3\":\"3.221545\"},{\"1\":\"8.304476\",\"2\":\"2.554288\",\"3\":\"4.264149\"},{\"1\":\"6.417455\",\"2\":\"4.622928\",\"3\":\"4.418698\"},{\"1\":\"5.190959\",\"2\":\"9.400145\",\"3\":\"5.365506\"},{\"1\":\"7.365883\",\"2\":\"9.782264\",\"3\":\"4.573154\"},{\"1\":\"1.346666\",\"2\":\"1.174874\",\"3\":\"1.469622\"},{\"1\":\"6.569923\",\"2\":\"4.749971\",\"3\":\"2.125528\"},{\"1\":\"7.050648\",\"2\":\"5.603327\",\"3\":\"5.952812\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nUsing QR decomposition, we get the following coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# we need to add a column of 1's to get beta_0 for the intercept\nintercept = rep(1, 10)\nQR = qr(cbind(intercept, mlr[, 1:2])) \nbetas = solve.qr(QR, mlr$y)\nbetas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nintercept        x1        x2 \n0.1672438 0.4908812 0.1964567 \n```\n:::\n:::\n\n\nAnd we get the following coefficients in the linear model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(y ~ ., data=mlr))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)          x1          x2 \n  0.1672438   0.4908812   0.1964567 \n```\n:::\n:::\n\n\nThe following code chunk shows how the earlier interactive plot was generated. Note the following:\n\n-   The value of `y` defined by the plane at (`x1`, `x2`) = (0,0) is $\\beta_0$ (shown by the red dot).\n\n-   The slope of the line at the intersection of the plane with the `x1` axis is $\\beta_1$.\n\n-   The slope of the line at the intersection of the plane with the `x2` axis is $\\beta_2$,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# define the bast fit plane using the betas from QR decomposition\nplane = tibble(x1=c(0, 10, 0, 10),\n               x2=c(0, 0, 10, 10),\n               y=c(betas[1], betas[1]+10*betas[2], betas[1]+10*betas[3], betas[1]+sum(10*betas[2:3])))\n\n# use plotly for interactive 3D graphs\nplot_ly() %>%\n  # add the points to the graph\n  add_trace(data = mlr, x=~x1, y = ~x2, z = ~y, type='scatter3d', mode='markers', \n            marker=list(color='black', size=7), showlegend=FALSE) %>%\n  # add the plane\n  add_trace(data = plane, x=~x1, y = ~x2, z = ~y, type='mesh3d', \n            facecolor=c('blue', 'blue'), opacity = 0.75, showlegend=FALSE) %>%\n  # add the red dot\n  add_trace(x=0, y=0, z=betas[1], type='scatter3d', mode='markers',\n            marker=list(color='red', size=7), showlegend=FALSE) %>%\n  # adjust the layout\n  layout(title = 'Best Fit Plane', showlegend = FALSE,\n         scene = list(xaxis = list(range=c(0,10)),\n                      yaxis = list(range=c(0,10)),\n                      camera = list(eye = list(x = 0, y = -2, z = 0.3))))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-f4997105858173027594\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f4997105858173027594\">{\"x\":{\"visdat\":{\"2ba07b554f3\":[\"function () \",\"plotlyVisDat\"],\"2ba05bd476f\":[\"function () \",\"data\"],\"2ba0433b6139\":[\"function () \",\"data\"]},\"cur_data\":\"2ba0433b6139\",\"attrs\":{\"2ba05bd476f\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":7},\"showlegend\":false,\"inherit\":true},\"2ba0433b6139\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"mesh3d\",\"facecolor\":[\"blue\",\"blue\"],\"opacity\":0.75,\"showlegend\":false,\"inherit\":true},\"2ba0433b6139.1\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":0,\"y\":0,\"z\":0.167243763471059,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"red\",\"size\":7},\"showlegend\":false,\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Best Fit Plane\",\"showlegend\":false,\"scene\":{\"xaxis\":{\"range\":[0,10],\"title\":\"x1\"},\"yaxis\":{\"range\":[0,10],\"title\":\"x2\"},\"camera\":{\"eye\":{\"x\":0,\"y\":-2,\"z\":0.3}},\"zaxis\":{\"title\":\"y\"}},\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[9.14806043496355,9.37075413297862,2.86139534786344,8.30447626067325,6.41745518893003,5.19095949130133,7.36588314641267,1.3466659723781,6.56992290401831,7.05064784036949],\"y\":[4.5774177624844,7.19112251652405,9.34672247152776,2.55428824340925,4.62292822543532,9.40014522755519,9.78226428385824,1.17487361654639,4.74997081561014,5.60332746244967],\"z\":[5.99114356409588,7.11473922517624,3.22154518985722,4.26414945838675,4.41869783432461,5.3655056340129,4.57315445009747,1.46962155854145,2.1255277574059,5.95281211087115],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":7,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"showlegend\":false,\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"colorbar\":{\"title\":\"y<br />y\",\"ticklen\":2},\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":true,\"x\":[0,10,0,10],\"y\":[0,0,10,10],\"z\":[0.167243763471059,5.07605548829849,2.13181054993435,7.04062227476178],\"type\":\"mesh3d\",\"facecolor\":[\"blue\",\"blue\"],\"opacity\":0.75,\"showlegend\":false,\"frame\":null},{\"x\":[0],\"y\":[0],\"z\":[0.167243763471059],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"red\",\"size\":7,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"showlegend\":false,\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n## Multiple Linear Regression in *R*\n\n::: callout-note\nThis section is the result of a collaborative effort with Dr. Stephen E. Gillespie.\n:::\n\nBelow is a short example on doing multiple linear regression in *R*. This example uses a data set on patient satisfaction as a function of their age, illness severity, anxiety level, and a surgery variable (this is a binary variable, we will ignore for this exercise). We will attempt to model patient satisfaction as a function of age, illness severity, and anxiety level. First, read the data and build the linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read the data\npt <- read.csv('data/PatientSatData.csv', sep = ',', header = T)\n\n# let's drop SurgMed as we're not going to use it\npt <- pt %>% select(-SurgMed)\n\n# View the data\npt\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Age\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"illSeverity\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Anxiety\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Satisfaction\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"55\",\"2\":\"50\",\"3\":\"2.1\",\"4\":\"68\"},{\"1\":\"46\",\"2\":\"24\",\"3\":\"2.8\",\"4\":\"77\"},{\"1\":\"30\",\"2\":\"46\",\"3\":\"3.3\",\"4\":\"96\"},{\"1\":\"35\",\"2\":\"48\",\"3\":\"4.5\",\"4\":\"80\"},{\"1\":\"59\",\"2\":\"58\",\"3\":\"2.0\",\"4\":\"43\"},{\"1\":\"61\",\"2\":\"60\",\"3\":\"5.1\",\"4\":\"44\"},{\"1\":\"74\",\"2\":\"65\",\"3\":\"5.5\",\"4\":\"26\"},{\"1\":\"38\",\"2\":\"42\",\"3\":\"3.2\",\"4\":\"88\"},{\"1\":\"27\",\"2\":\"42\",\"3\":\"3.1\",\"4\":\"75\"},{\"1\":\"51\",\"2\":\"50\",\"3\":\"2.4\",\"4\":\"57\"},{\"1\":\"53\",\"2\":\"38\",\"3\":\"2.2\",\"4\":\"56\"},{\"1\":\"41\",\"2\":\"30\",\"3\":\"2.1\",\"4\":\"88\"},{\"1\":\"37\",\"2\":\"31\",\"3\":\"1.9\",\"4\":\"88\"},{\"1\":\"24\",\"2\":\"34\",\"3\":\"3.1\",\"4\":\"102\"},{\"1\":\"42\",\"2\":\"30\",\"3\":\"3.0\",\"4\":\"88\"},{\"1\":\"50\",\"2\":\"48\",\"3\":\"4.2\",\"4\":\"70\"},{\"1\":\"58\",\"2\":\"61\",\"3\":\"4.6\",\"4\":\"52\"},{\"1\":\"60\",\"2\":\"71\",\"3\":\"5.3\",\"4\":\"43\"},{\"1\":\"62\",\"2\":\"62\",\"3\":\"7.2\",\"4\":\"46\"},{\"1\":\"68\",\"2\":\"38\",\"3\":\"7.8\",\"4\":\"56\"},{\"1\":\"70\",\"2\":\"41\",\"3\":\"7.0\",\"4\":\"59\"},{\"1\":\"79\",\"2\":\"66\",\"3\":\"6.2\",\"4\":\"26\"},{\"1\":\"63\",\"2\":\"31\",\"3\":\"4.1\",\"4\":\"52\"},{\"1\":\"39\",\"2\":\"42\",\"3\":\"3.5\",\"4\":\"83\"},{\"1\":\"49\",\"2\":\"40\",\"3\":\"2.1\",\"4\":\"75\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNote that our data is formatted in numeric format, which is what we need for this sort of modeling.\n\nWe can look at our data. In multiple regression, `pairs` is useful.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(pt)\n```\n\n::: {.cell-output-display}\n![](mlr_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWe can see some useful things:\n\n1.  Age and satisfaction appear to have a linear relationship (the bottom left corner)\n\n2.  Illness severity and satisfaction appear to have a linear relationship, though not as strongly\n\n3.  It's less clear for anxiety and satisfaction.\n\n4.  Age and illness severity do not appear to have a relationship.\n\n5.  Age and anxiety might have a relationship, but its not fully clear.\n\n6.  Illness severity and anxiety do not appear to have a relationship\n\nModel the data. Note how this format is analogous to ANOVA with multiple factors and simple linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nptLM <- lm(Satisfaction ~ Age + illSeverity + Anxiety, data = pt)\n```\n:::\n\n\nWe can now view our model results. We will use $\\alpha = .05$ as our appropriate significance level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# we view the summary results\nsummary(ptLM)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Satisfaction ~ Age + illSeverity + Anxiety, data = pt)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-18.2812  -3.8635   0.6427   4.5324  11.8734 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 143.8952     5.8975  24.399  < 2e-16 ***\nAge          -1.1135     0.1326  -8.398 3.75e-08 ***\nillSeverity  -0.5849     0.1320  -4.430 0.000232 ***\nAnxiety       1.2962     1.0560   1.227 0.233231    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.037 on 21 degrees of freedom\nMultiple R-squared:  0.9035,\tAdjusted R-squared:  0.8897 \nF-statistic: 65.55 on 3 and 21 DF,  p-value: 7.85e-11\n```\n:::\n:::\n\n\nWe see several things. First, we can say that the intercept, age, and illness severity are all statistically significant. Anxiety does not appear to be significant. As expected given our individual results, our F-statistic (sometimes called a model utility test) shows us that there is at least one predictor that is significant. Further we can see that our $R^2$ and $R_{adj}^2$ are both relatively high, which shows that these predictors explain much of the variability in the data. We can see our RSE is about 7, which is not too extreme given our the range on our outputs.\n\nAs we do not find anxiety significant, we can drop it as an independent variable (we discuss model selection in the next chapter). Our new model is then:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nptLM2 <- lm(Satisfaction ~ Age + illSeverity, data = pt)\nsummary(ptLM2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Satisfaction ~ Age + illSeverity, data = pt)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-17.2800  -5.0316   0.9276   4.2911  10.4993 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 143.4720     5.9548  24.093  < 2e-16 ***\nAge          -1.0311     0.1156  -8.918 9.28e-09 ***\nillSeverity  -0.5560     0.1314  -4.231 0.000343 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.118 on 22 degrees of freedom\nMultiple R-squared:  0.8966,\tAdjusted R-squared:  0.8872 \nF-statistic: 95.38 on 2 and 22 DF,  p-value: 1.446e-11\n```\n:::\n:::\n\n\nWe get similar results. We can then build our linear model:\n\n$$[Patient Satisfaction] = 143 + -1.03[Age] + -0.556[Illness Severity] + \\epsilon$$\n\n### Interpretation\n\nWe can interpret this as saying that for every additional year of age, a patient's satisfaction drops about a point and for every additional point of illness severity, a patient loses about half a point of satisfaction. That is, the older and sicker you are, the less likely you are to be satisfied. This generally seems to make sense.\n\n### Confidence Intervals\n\nMoreover, we can use the model to show our confidence intervals on our coefficients using `confint`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(ptLM2, level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 131.122434 155.8215898\nAge          -1.270816  -0.7912905\nillSeverity  -0.828566  -0.2835096\n```\n:::\n\n```{.r .cell-code}\n# We can then say, with 95% confidence that our intercept is in the interval ~ (131, 156)\n```\n:::\n\n\n::: callout-note\n`confint` requires:\n\n1.  A model, called `ptLM2` in this case.\n\n2.  You can also pass it your 1-alpha level (the default is alpha = .05, or .95 confidence).\n\n3.  You can also pass it specific parameters to check (useful if working with amodel with many parameters).\n:::\n\n### Predictions\n\nWe can use our model to predict a patient's satisfaction given their age and illness severity using `predict` in the same manner as simple linear regression. For a point estimate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(ptLM2, list(Age = 35, illSeverity=50))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n79.58325 \n```\n:::\n:::\n\n\nAn individual response will be in this interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(ptLM2,list(Age=35, illSeverity=50),interval=\"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       fit      lwr      upr\n1 79.58325 63.87546 95.29105\n```\n:::\n:::\n\n\nThe mean response for someone with these inputs will be:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(ptLM2,list(Age=35, illSeverity=50),interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       fit      lwr      upr\n1 79.58325 74.21262 84.95388\n```\n:::\n:::\n\n\nWe can also plot these values. Note that our result with two predictors is a plane in this case. With 3+ predictors, it is a hyperplane. Often, we will plot either a contour map where each line corresponds to a fixed level of a predictor or just choose a single predictor.\n\nWe can produce a contour plot using `geom_contour` (one can also use `stat_contour`). Of course, this works for two predictors. As the number of independent variables increases, visualizing the data becomes somewhat more challenging and requires visualizing the solution only a few dimensions at a time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Requires a set of points with predictions:\n# Produce a data frame that is every combination of Age and issEverity\nmySurface <- expand_grid( \n  Age = seq(min(pt$Age), max(pt$Age), by = 1), \n  illSeverity = seq(min(pt$illSeverity), max(pt$illSeverity), by = 1)) \n\n# look at our data\nhead(mySurface)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Age\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"illSeverity\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"24\",\"2\":\"24\"},{\"1\":\"24\",\"2\":\"25\"},{\"1\":\"24\",\"2\":\"26\"},{\"1\":\"24\",\"2\":\"27\"},{\"1\":\"24\",\"2\":\"28\"},{\"1\":\"24\",\"2\":\"29\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNow add in our predictions. Recall `predict` takes a data frame with columns that have the same name as the variables in the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmySurface$Satisfaction <- predict(ptLM2, mySurface) \nhead(mySurface)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Age\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"illSeverity\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Satisfaction\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"24\",\"2\":\"24\",\"3\":\"105.3818\"},{\"1\":\"24\",\"2\":\"25\",\"3\":\"104.8258\"},{\"1\":\"24\",\"2\":\"26\",\"3\":\"104.2697\"},{\"1\":\"24\",\"2\":\"27\",\"3\":\"103.7137\"},{\"1\":\"24\",\"2\":\"28\",\"3\":\"103.1577\"},{\"1\":\"24\",\"2\":\"29\",\"3\":\"102.6016\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nPlot the contours for our response surface.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mySurface,\n       aes(x = Age, y = illSeverity, z = Satisfaction)) + \n  # you can use a number of ways to do this.  geom_contour works\n  geom_contour(aes(color = after_stat(level))) + \n  # This color argument varies the color of your contours by their level\n  scale_color_distiller(palette = 'Spectral', direction = -1) + \n  # clean up the plot\n  theme_minimal() + \n  xlab('Age') + ylab('Illness Severity') + \n  ggtitle('Patient Satisfaction Response Surface') \n```\n\n::: {.cell-output-display}\n![](mlr_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nWith this plot, we can clearly see at least two things:\n\n-   Our mathematical interpretation holds true. The younger and less severely ill the patient, the more satisfied they are (in general, as based on our model).\n-   Our model is a plane. We see this with the evenly spaced, linear contour lines.\n\nIt is also useful to overlay the actual observations on the plot. We can do this as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This is our original contour plot as produced above, with one exception.  \n# We move the data for the contour to the geom_contour so we can also plot the observations\nggplot() + \n  geom_contour(data = mySurface, aes(x = Age, y = illSeverity, z = Satisfaction, color = after_stat(level))) + \n  # This color argument varies the color of your contours by their level\n  scale_color_distiller(palette = 'Spectral', direction = -1) + \n  theme_minimal() + xlab('Age') + ylab('Illness Severity') + \n  ggtitle('Patient Satisfaction Response Surface')  + \n  geom_point(data = pt, aes(x = Age, y = illSeverity, color = Satisfaction))\n```\n\n::: {.cell-output-display}\n![](mlr_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n### Outliers\n\nBy plotting these points, we can compare our results (the contour lines) to the observations. The first thing this allows us to do is look for outliers. For example, there are two around the age 30 and a severity of illness; note how their colors are disjoint from what the contour colors predict. This, of course, is harder to interpret than a simple linear regression as it involves comparing colors. In general, it is easier to use the numbers for higher dimensional models. Second, we can get an idea of leverage or areas of our model that are not informed by data. For example, there are no observations in this region:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](mlr_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThat means that any predictions in this region are ill-informed and extrapolations beyond the data. In an advanced design section, we will discuss how ensuring we get \"coverage\" or \"space-filling\" is an important property for good experimental designs so we can avoid this problem.\n\n### Assumptions\n\nFinally, we can check our model to ensure that it is legitimate. Check assumptions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot our standard diagnostic plots\npar(mfrow = c(2,2))\nplot(ptLM2)\n```\n\n::: {.cell-output-display}\n![](mlr_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nIt appears that we meet our linearity, independence, normality and homoscedasticity assumptions. There are no significant patterns, though we may have a few unusual observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check normality\nshapiro.test(ptLM2$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  ptLM2$residuals\nW = 0.95367, p-value = 0.3028\n```\n:::\n:::\n\n\nCheck homoscedasticity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::ncvTest(ptLM2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNon-constant Variance Score Test \nVariance formula: ~ fitted.values \nChisquare = 1.380242, Df = 1, p = 0.24006\n```\n:::\n:::\n\n\nWe meet our assumptions, so also check for unusual observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We can identify points that have residuals greater than 2 standard deviations away from our model's prediction\nptLM2$residuals[abs(ptLM2$residuals) >= 2*sd(ptLM2$residuals)]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        9 \n-17.27998 \n```\n:::\n\n```{.r .cell-code}\n# Point 9 is an outlier\n```\n:::\n\n\nWe can check for leverage points with a number of ways. We'll check using Cook's distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(ptLM2, which = 4)\n```\n\n::: {.cell-output-display}\n![](mlr_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Again point 9 is a point of significant leverage. \n```\n:::\n\n\nBased on these results, we may consider dropping point nine. Before doing so, we should check for data entry errors or anything unusual about that data point. If we do drop it, we should note that we did so in our analysis.\n\nIf we do conclude that point nine should be dropped, we can build a new linear model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Just check the summary of the model with Point 9 dropped\nsummary(lm(Satisfaction ~ Age + illSeverity, data = pt[-9,]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Satisfaction ~ Age + illSeverity, data = pt[-9, \n    ])\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-11.870  -3.700   0.834   3.595  12.169 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 147.9415     5.2186  28.349  < 2e-16 ***\nAge          -1.1484     0.1044 -11.003 3.54e-10 ***\nillSeverity  -0.5054     0.1120  -4.513 0.000191 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.003 on 21 degrees of freedom\nMultiple R-squared:  0.9292,\tAdjusted R-squared:  0.9224 \nF-statistic: 137.8 on 2 and 21 DF,  p-value: 8.449e-13\n```\n:::\n:::\n\n\nNote that our standard errors decrease somewhat and our $R^2$ increases, indicating this is a better model (although on a smaller subset of the data).\n",
    "supporting": [
      "mlr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.0/htmlwidgets.js\"></script>\r\n<script src=\"../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\r\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\r\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}